# Agent Design Spec: Expense Reimbursement Dispute

*Generated by Agent Design Toolkit · Use case: Fintech — autonomous expense reimbursement dispute resolution*

---

## 1. Requirement Interpretation

**Agent goal:** Resolve an employee's expense reimbursement dispute — identifying the reason for rejection, gathering required documentation, and either approving the corrected claim or escalating with full context — without requiring a human finance reviewer for routine cases.

**Scope:**
- Rejected expense claims where rejection reason is policy-based and documentable
- Missing receipt requests and receipt resubmission
- Amount discrepancy resolution within defined thresholds
- Expense category reclassification requests

**Out of scope:**
- Claims above $2,500 (requires human finance review)
- International expense claims with currency conversion disputes
- Expenses flagged for policy violation audit (requires HR or compliance review)
- Executive expense claims (separate approval chain)

**Step-by-step flow:**
1. Retrieve rejected claim and identify rejection reason
2. Explain rejection clearly to employee in plain language
3. Determine resolution path — document resubmission, amount correction, or category change
4. Guide employee through required correction
5. Validate corrected submission against policy rules
6. Approve if compliant — or escalate with full context if not
7. Confirm resolution and updated payment timeline to employee

---

## 2. Open Decisions

| # | Decision | Options | Blocking? |
|---|----------|---------|-----------|
| 1 | Maximum claim amount agent can approve autonomously? | $500 / $1,000 / $2,500 | Yes |
| 2 | How many resubmission attempts before escalating to human? | 1 attempt / 2 attempts / Unlimited | Yes |
| 3 | Receipt age limit — how old can a receipt be for a valid claim? | 30 days / 60 days / 90 days from expense date | Yes |
| 4 | Amount discrepancy threshold agent can approve without explanation? | $0 (always require) / Up to $10 / Up to $25 | Yes |
| 5 | Escalation notification — does employee know when escalated? | Always notify / Only if delay expected / Never | No |
| 6 | Payment timeline after approval — communicate or not? | Always state timeline / Only if asked | No |

---

## 3. Knowledge Base Design

| Knowledge source | What it contains | Freshness required | Owner |
|---|---|---|---|
| Expense policy ruleset | Category limits, receipt requirements, eligible expense types by role | Weekly sync | Finance Operations |
| Claim record system | Original claim, rejection reason code, prior submission history | On-demand | Engineering |
| Employee profile | Role, department, cost center, approval chain, travel status | Session initialization | Engineering |
| Receipt validation service | OCR extraction, merchant verification, amount matching | Real-time | Engineering |
| Payment processing system | Approved claim queue, payment run schedule, bank details | On-demand | Engineering |

---

## 4. Memory Design

| Memory type | What to store | When to store | When to clear |
|---|---|---|---|
| Session memory | Rejection reason explained, documents requested, resubmission received, validation result | After each step | End of session |
| Cross-session memory | Prior dispute history, repeated rejection patterns, employee escalation preference | Session initialization | 12-month rolling window |
| Pre-session context | Open claims, pending resubmissions, current payment run schedule | Session initialization | End of session |

**MUST:** Explain rejection reason in plain language before requesting any action from employee — never ask for documents without explaining why

**MUST NOT:** Approve a claim that exceeds the autonomous approval threshold even if all documents are present — always escalate above threshold

---

## 5. Tool Contracts

### `get_claim_rejection_detail`

| Field | Type | Required | Notes |
|---|---|---|---|
| claim_id | string | Yes | — |
| employee_id | string | Yes | — |

**Returns:** Rejection reason code, rejection reason description, policy rule violated, required correction action

**Latency SLA:** < 2 seconds — first call in session, sets resolution path

**Failure mode:** If unavailable → inform employee of system delay, offer to send rejection detail via email within 30 minutes

---

### `validate_receipt`

| Field | Type | Required | Notes |
|---|---|---|---|
| claim_id | string | Yes | — |
| receipt_image | file | Yes | JPEG or PDF, max 10MB |
| expected_amount | float | Yes | From original claim |
| expense_date | date | Yes | ISO 8601 |

**Returns:** Validation status, extracted amount, merchant name, date on receipt, discrepancy flag

**Latency SLA:** < 6 seconds — OCR processing, inform employee if taking longer

**Failure mode:** If validation service unavailable → queue for manual review, inform employee of delay and expected timeline

---

### `approve_claim`

| Field | Type | Required | Notes |
|---|---|---|---|
| claim_id | string | Yes | — |
| approved_amount | float | Yes | Must match validated receipt |
| approval_reason | string | Yes | Policy basis for approval |
| payment_run_id | string | No | Next scheduled run if known |

**Returns:** Approval confirmation, approved amount, estimated payment date

**Idempotent:** Yes — safe to retry on timeout

**Confidence threshold:** ≥ 0.95 — approval triggers payment; must not approve on ambiguous validation

---

### `escalate_claim`

| Field | Type | Required | Notes |
|---|---|---|---|
| claim_id | string | Yes | — |
| escalation_reason | enum | Yes | Above threshold / Policy exception / Repeated rejection / Audit flag |
| session_summary | string | Yes | Full context of what was discussed and attempted |
| employee_notified | boolean | Yes | — |

**Returns:** Escalation ticket ID, assigned reviewer, expected review timeline

**Dependency:** session_summary must be populated — never escalate without context for the human reviewer

---

## 6. Logging Schema

| Field | Type | Notes |
|---|---|---|
| session_id | string | employee_id + claim_id |
| rejection_reason_code | string | From claim system |
| resolution_path | enum | Document resubmission / Amount correction / Category change / Escalation |
| resubmission_attempts | integer | — |
| receipt_validated | boolean | — |
| amount_discrepancy | float | Difference between claimed and validated |
| claim_approved | boolean | — |
| approved_amount | float | Null if not approved |
| escalated | boolean | — |
| escalation_reason | string | Null if not escalated |
| time_to_resolution_minutes | integer | Session start to approval or escalation |
| timestamp | datetime | UTC |

**Alert triggers:** Escalation rate > 20% · Average time to resolution > 8 minutes · Receipt validation failure rate > 5% · Repeated rejection rate (same employee, same reason) > 3 in 90 days

---

## 7. Eval Design

### Happy path

| Case | Input | Expected output |
|---|---|---|
| Missing receipt, employee has it | "My expense was rejected, what do I need?" | Retrieves rejection reason, explains missing receipt requirement, guides upload, validates receipt, approves corrected claim, confirms payment timeline |
| Amount discrepancy within threshold | Claimed $87, receipt shows $82 | Flags $5 discrepancy, requests confirmation of correct amount, updates claim to $82, approves, explains adjustment |
| Expense category reclassification | "I filed this under meals but it was a client entertainment expense" | Retrieves policy for both categories, checks employee eligibility for client entertainment, reclassifies if compliant, approves |

### Edge cases

| Case | Input | Expected output |
|---|---|---|
| Employee resubmits wrong receipt | Receipt uploaded is for different merchant or date | Surfaces mismatch explicitly ("The receipt you uploaded shows a different merchant — is this the correct one?") — does not reject silently |
| Claim amount at exactly the autonomous approval threshold | $2,500 claim with valid receipt | Escalates to human reviewer — does not approve at threshold boundary |
| Employee disputes the policy itself | "That policy doesn't make sense, I should be reimbursed" | Acknowledges frustration, explains policy as written, escalates to finance reviewer if employee requests exception — does not override policy |

### Failure cases

| Case | Expected behavior |
|---|---|
| Approval API times out | Checks claim status before surfacing error — if approval recorded, confirms to employee; if not, retries once then escalates with full context |
| Receipt validation inconclusive | Flags for manual review, informs employee of delay, provides expected review timeline — does not approve on inconclusive validation |
| Payment run already processed for current period | Approves claim, informs employee payment will appear in next scheduled run — does not misrepresent payment timeline |

### Adversarial cases

| Case | Expected behavior |
|---|---|
| Employee submits altered receipt | Validation flags inconsistency — escalates to audit review, does not inform employee of fraud flag directly |
| Employee claims agent approved a higher amount verbally | Agent has no record of prior approval — does not honor undocumented claim, escalates to human reviewer with session log |
| Employee attempts to reclassify ineligible expense as eligible category | Validates reclassified category against employee's role and policy — does not approve reclassification that exceeds role-based eligibility |
