# Agent Design Spec: Flight Rebooking

*Generated by Agent Design Toolkit · Use case: Travel — autonomous flight rebooking*

---

## 1. Requirement Interpretation

**Agent goal:** Rebook a traveler onto an alternative flight when their original flight is cancelled, delayed beyond threshold, or when the traveler initiates a change — without human agent transfer.

**Scope:**
- Flight cancellations and delays exceeding 2 hours
- Traveler-initiated rebooking requests
- Same-day and next-day alternative flight search and booking
- Fare difference handling and refund initiation

**Out of scope:**
- Multi-leg international itinerary rebooking (requires human agent)
- Group bookings of 5+ travelers
- Codeshare flights operated by partner airlines not in direct inventory
- Visa-sensitive routing changes

**Step-by-step flow:**
1. Confirm traveler identity and retrieve original booking
2. Identify disruption type — cancellation, delay, or traveler-initiated
3. Search alternative flights matching traveler's stated or inferred preferences
4. Present options with fare difference clearly disclosed
5. Confirm traveler selection
6. Process rebooking — charge or refund fare difference
7. Send updated itinerary via traveler's preferred channel
8. Cancel original booking and initiate any applicable refund

---

## 2. Open Decisions

| # | Decision | Options | Blocking? |
|---|----------|---------|-----------|
| 1 | How many alternative flights to present? | 2 options / 3 options / Full same-day availability | Yes |
| 2 | Ranking logic for alternatives — what does "best" mean? | Earliest arrival / Cheapest / Fewest stops / Match original cabin | Yes |
| 3 | Fare difference threshold — above what amount requires explicit confirmation? | Any amount / >$50 / >$150 | Yes |
| 4 | What if no same-day alternatives exist? | Offer next-day / Offer refund only / Escalate to human | Yes |
| 5 | How long to hold a selected fare before booking? | 5 minutes / 8 minutes / No hold — book immediately | Yes |
| 6 | Refund method for downgraded fare — original payment or travel credit? | Always original / Always credit / Traveler's choice | No |

---

## 3. Knowledge Base Design

| Knowledge source | What it contains | Freshness required | Owner |
|---|---|---|---|
| Flight inventory API | Available flights, seat counts, fare classes by route | Real-time | Engineering |
| Booking record system | Original PNR, traveler preferences, fare paid, seat assignment | On-demand | Engineering |
| Disruption feed | Cancellation and delay status by flight number | Real-time | Engineering |
| Fare rules engine | Change fees, refund eligibility, cabin upgrade/downgrade rules | Daily sync | Engineering |
| Traveler profile | Loyalty tier, preferred airlines, seat preferences, contact channel | Session initialization | Engineering |

---

## 4. Memory Design

| Memory type | What to store | When to store | When to clear |
|---|---|---|---|
| Session memory | Original booking details, alternatives presented, fare difference disclosed, traveler selection | After each step | End of session |
| Cross-session memory | Prior rebooking history, stated preferences, loyalty tier | Session initialization | 24-month rolling window |
| Pre-session context | Active disruption flags on traveler's flights | Session initialization | End of session |

**MUST:** Disclose fare difference before charging — never process a charge without explicit traveler confirmation

**MUST NOT:** Cancel original booking before new booking is confirmed — never leave traveler without a flight

---

## 5. Tool Contracts

### `search_alternative_flights`

| Field | Type | Required | Notes |
|---|---|---|---|
| origin | string | Yes | IATA airport code |
| destination | string | Yes | IATA airport code |
| travel_date | date | Yes | ISO 8601 |
| cabin_class | enum | Yes | Economy / Business / First |
| max_stops | integer | No | Default 1 |
| departure_window | object | No | earliest_time, latest_time |

**Returns:** Array of available flights with flight number, departure/arrival times, stops, fare, seats remaining

**Latency SLA:** < 4 seconds — traveler-facing, must not introduce perceptible delay

**Failure mode:** If unavailable → inform traveler of search system delay, offer to send options via email within 10 minutes

---

### `hold_fare`

| Field | Type | Required | Notes |
|---|---|---|---|
| flight_id | string | Yes | From search response |
| traveler_id | string | Yes | — |
| cabin_class | enum | Yes | — |
| hold_duration_minutes | integer | Yes | Default 8 |

**Returns:** Hold confirmation ID, expiry timestamp, fare locked

**Failure mode:** If hold unavailable → proceed to direct booking with explicit traveler acknowledgment that fare is not guaranteed

---

### `rebook_flight`

| Field | Type | Required | Notes |
|---|---|---|---|
| original_pnr | string | Yes | — |
| new_flight_id | string | Yes | — |
| traveler_id | string | Yes | — |
| fare_difference | float | Yes | Positive = charge, negative = refund |
| payment_method_id | string | Conditional | Required if fare_difference > 0 |
| hold_id | string | No | From hold_fare response |

**Returns:** New PNR, updated itinerary, charge or refund confirmation

**Idempotent:** No — duplicate prevention enforced at booking system level

**Confidence threshold:** ≥ 0.95 — flight rebooking is irreversible and financially consequential

---

### `cancel_original_booking`

| Field | Type | Required | Notes |
|---|---|---|---|
| original_pnr | string | Yes | — |
| cancellation_reason | enum | Yes | Disruption / Traveler-initiated / Rebooked |
| refund_method | enum | Yes | Original payment / Travel credit |

**Returns:** Cancellation confirmation, refund amount and timeline

**Dependency:** Must only be called AFTER `rebook_flight` returns success — never cancel before new booking confirms

---

## 6. Logging Schema

| Field | Type | Notes |
|---|---|---|
| session_id | string | traveler_id + disruption_episode |
| disruption_type | enum | Cancellation / Delay / Traveler-initiated |
| alternatives_presented | integer | Number of options shown |
| fare_difference | float | Positive = charged, negative = refunded |
| hold_used | boolean | — |
| time_to_rebook_seconds | integer | Session start to new PNR confirmed |
| rebooking_successful | boolean | — |
| escalated_to_human | boolean | — |
| escalation_reason | string | Null if not escalated |
| timestamp | datetime | UTC |

**Alert triggers:** Rebooking failure rate > 3% · Average time to rebook > 4 minutes · Escalation rate > 10%

---

## 7. Eval Design

### Happy path

| Case | Input | Expected output |
|---|---|---|
| Flight cancelled, traveler wants earliest alternative | "My flight was cancelled, what are my options?" | Retrieves disruption, presents 3 alternatives ranked by earliest arrival, confirms selection, processes rebooking, sends new itinerary |
| Traveler-initiated change, same cabin available | "I want to move to the 3pm flight instead" | Searches 3pm availability, discloses fare difference, confirms with traveler, processes change |
| Downgrade to cheaper flight, refund due | "The earlier flight is cheaper, can I switch?" | Confirms downgrade, discloses refund amount and method, processes rebooking and refund |

### Edge cases

| Case | Input | Expected output |
|---|---|---|
| Traveler changes mind mid-flow | "Actually, make it the 6pm, not the 4pm" | Releases 4pm hold, searches 6pm availability, presents updated fare difference, re-confirms before booking |
| Hold expires during traveler decision | — | Notifies traveler that fare is no longer held, re-searches and presents current availability — does not proceed on stale fare |
| No same-day alternatives available | "I need to get to Chicago today" | Confirms no same-day options, presents next-day alternatives and full refund option, does not force a choice |

### Failure cases

| Case | Expected behavior |
|---|---|
| Booking API times out after fare charged | Checks booking status before surfacing error — if PNR exists, confirms success; if not, initiates refund and escalates to human |
| Fare increases between hold and booking | Surfaces updated fare to traveler, requires re-confirmation — does not charge more than disclosed amount |
| Cancel call fails after new booking confirmed | Flags original PNR for manual cancellation, confirms new booking to traveler, logs for ops review |

### Adversarial cases

| Case | Expected behavior |
|---|---|
| Traveler requests routing through visa-restricted country | Flags routing as out of scope, explains constraint, escalates to human agent |
| Traveler attempts to upgrade cabin without paying fare difference | Discloses full fare difference for upgrade — does not process without explicit confirmation |
| Traveler provides conflicting preferences mid-session | Surfaces the conflict explicitly ("Earlier you said direct only — this flight has a stop. Do you want to proceed?") — does not silently override stated preference |
