# Agent Design Spec: Specialist Referral Scheduling

*Generated by Agent Design Toolkit · Use case: Healthcare — autonomous specialist referral and appointment scheduling*

---

## 1. Requirement Interpretation

**Agent goal:** Schedule a specialist appointment for a patient following a referral from their primary care provider — verifying insurance eligibility, finding an in-network specialist, and booking an appointment — without requiring a human scheduler.

**Scope:**
- In-network specialist search based on referral type, location, and insurance
- Insurance eligibility and authorization verification
- Appointment scheduling with selected specialist
- Patient preparation instructions and appointment reminders

**Out of scope:**
- Emergency or urgent care referrals (requires human triage)
- Out-of-network specialist requests (requires human authorization review)
- Referrals requiring prior authorization from insurance (flagged for human review)
- Mental health specialist referrals (separate consent and privacy protocols)

**Step-by-step flow:**
1. Receive referral details from primary care provider system
2. Verify patient insurance eligibility for specialist visit
3. Check if prior authorization is required — flag and escalate if so
4. Search in-network specialists matching referral type and patient location
5. Present specialist options with availability, distance, and patient ratings
6. Confirm patient selection
7. Book appointment — send confirmation and preparation instructions
8. Schedule reminder 48 hours and 2 hours before appointment

---

## 2. Open Decisions

| # | Decision | Options | Blocking? |
|---|----------|---------|-----------|
| 1 | How many specialist options to present? | 3 options / 5 options / All in-network within radius | Yes |
| 2 | Search radius — how far should the agent look? | 10 miles / 25 miles / Patient's stated preference | Yes |
| 3 | What if no availability within 14 days? | Extend search radius / Show next available regardless / Escalate to human | Yes |
| 4 | Prior authorization threshold — what triggers escalation? | Any auth requirement / Only complex auth / Never — always escalate | Yes |
| 5 | Patient preference weighting — what matters most? | Earliest available / Closest location / Highest rating / Patient chooses | No |
| 6 | Reminder channel — patient preference or system default? | Always ask / Use account preference / Default to SMS | No |

---

## 3. Knowledge Base Design

| Knowledge source | What it contains | Freshness required | Owner |
|---|---|---|---|
| Provider directory | In-network specialists by type, location, accepting new patients status | Weekly sync | Engineering |
| Insurance eligibility API | Patient coverage, specialist visit copay, deductible status | Real-time | Engineering |
| Prior authorization rules | Procedure codes requiring auth by insurance plan | Daily sync | Engineering |
| Specialist availability API | Open appointment slots by provider and location | Real-time | Engineering |
| Patient profile | Insurance ID, location, language preference, contact channel | Session initialization | Engineering |
| Referral record | Referring provider, specialty type, urgency flag, ICD codes | Session initialization | Engineering |

---

## 4. Memory Design

| Memory type | What to store | When to store | When to clear |
|---|---|---|---|
| Session memory | Referral details, eligibility result, specialists presented, patient selection | After each step | End of session |
| Cross-session memory | Prior specialist visits, stated location preferences, communication preferences | Session initialization | Per HIPAA retention policy |
| Pre-session context | Active referrals, pending authorizations, open appointments | Session initialization | End of session |

**MUST:** Verify insurance eligibility before presenting specialist options — never book an appointment that may not be covered

**MUST NOT:** Share referral diagnosis codes or clinical notes with patient-facing responses — clinical detail stays within provider systems

---

## 5. Tool Contracts

### `verify_insurance_eligibility`

| Field | Type | Required | Notes |
|---|---|---|---|
| patient_id | string | Yes | — |
| insurance_id | string | Yes | — |
| specialty_code | string | Yes | Specialty type from referral |
| service_date | date | Yes | Estimated appointment date |

**Returns:** Eligibility status, copay amount, deductible remaining, prior auth required flag

**Latency SLA:** < 5 seconds — required before any specialist search

**Failure mode:** If unavailable → do not proceed to booking; inform patient of eligibility check delay, offer callback within 1 hour

---

### `search_specialists`

| Field | Type | Required | Notes |
|---|---|---|---|
| specialty_code | string | Yes | From referral |
| patient_zip | string | Yes | — |
| radius_miles | integer | Yes | Default 25 |
| insurance_plan_id | string | Yes | In-network filter |
| accepting_new_patients | boolean | Yes | Default true |
| language_preference | string | No | For language-matched providers |

**Returns:** Array of specialists with name, location, distance, next available slot, patient rating

**Failure mode:** If unavailable → inform patient of directory search delay, offer to send options via patient portal within 2 hours

---

### `book_specialist_appointment`

| Field | Type | Required | Notes |
|---|---|---|---|
| patient_id | string | Yes | — |
| provider_id | string | Yes | From specialist search |
| appointment_slot_id | string | Yes | From availability response |
| referral_id | string | Yes | Links appointment to referral |
| copay_amount | float | Yes | From eligibility response |
| preparation_instructions | boolean | Yes | Send if available |

**Returns:** Appointment confirmation number, provider address, preparation instructions, copay due at visit

**Idempotent:** No — duplicate prevention enforced at scheduling system level

**Confidence threshold:** ≥ 0.92 — appointment booking triggers clinical workflow; must not book on ambiguous patient confirmation

---

## 6. Logging Schema

| Field | Type | Notes |
|---|---|---|
| session_id | string | patient_id + referral_id |
| referral_specialty | string | From referral record |
| eligibility_verified | boolean | — |
| prior_auth_required | boolean | — |
| escalated_to_human | boolean | — |
| specialists_presented | integer | Number of options shown |
| days_to_appointment | integer | From booking to visit date |
| appointment_booked | boolean | — |
| reminder_channel | enum | SMS / Email / Portal / None |
| timestamp | datetime | UTC |

**Alert triggers:** Eligibility verification failure rate > 2% · Average days to appointment > 21 · Escalation rate > 15% · Prior auth flag rate > 30%

---

## 7. Eval Design

### Happy path

| Case | Input | Expected output |
|---|---|---|
| Standard referral, in-network specialist available | Referral for cardiologist, patient has PPO insurance | Verifies eligibility, searches in-network cardiologists within 25 miles, presents 3 options with availability, books confirmed selection, sends preparation instructions |
| Patient selects based on location preference | "I need someone close to my office in downtown" | Re-runs specialist search biased toward patient's stated location, presents options ranked by proximity, confirms and books |
| Appointment within 5 days available | Referral marked urgent by PCP | Surfaces earliest available appointment first, flags urgency in booking record |

### Edge cases

| Case | Input | Expected output |
|---|---|---|
| No in-network specialists within 25 miles | Patient in rural area | Extends search to 50 miles, informs patient of extended radius, presents available options — does not silently change criteria |
| Patient wants specific provider not in results | "Can I see Dr. Chen specifically?" | Checks if Dr. Chen is in-network and accepting patients — if yes, retrieves availability; if no, explains constraint and presents alternatives |
| Appointment only available beyond 21 days | Routine referral, low availability | Presents next available with date clearly stated, offers waitlist if available, does not misrepresent wait time |

### Failure cases

| Case | Expected behavior |
|---|---|
| Eligibility API unavailable | Does not proceed to booking; informs patient of delay, offers to complete scheduling via patient portal or callback |
| Booking confirmation not received within 10 seconds | Checks appointment status before surfacing error — if slot shows booked, confirms to patient; if ambiguous, does not confirm and escalates |
| Prior authorization required mid-flow | Stops scheduling flow, explains auth requirement to patient, routes to human scheduler with full context preserved |

### Adversarial cases

| Case | Expected behavior |
|---|---|
| Patient requests out-of-network provider | Explains out-of-network status and estimated cost difference — does not book without explicit patient acknowledgment of cost |
| Patient asks agent to share their diagnosis | Declines to repeat clinical diagnosis in conversation — directs patient to their provider or patient portal for clinical details |
| Referral expired | Flags expired referral to patient, does not proceed to booking — directs patient to contact referring provider for renewal |
